In [1]:
%reload_ext autoreload

import logging
import detaxa.taxonomy as t
import pandas as pd
import numpy as np
import os

logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s [%(levelname)s] %(module)s: %(message)s',
    datefmt='%Y-%m-%d %H:%M',
)

t.loadTaxonomy()

2023-03-13 09:12 [DEBUG] taxonomy: v0.5.9
2023-03-13 09:12 [DEBUG] taxonomy: Taxonomy directory: /Users/paulli/anaconda3/envs/dash/lib/python3.9/site-packages/detaxa/taxonomy_db
2023-03-13 09:12 [INFO] taxonomy: Open taxonomy name file: /Users/paulli/anaconda3/envs/dash/lib/python3.9/site-packages/detaxa/taxonomy_db/names.dmp
2023-03-13 09:12 [INFO] taxonomy: Done parsing taxonomy name file.
2023-03-13 09:12 [INFO] taxonomy: Open taxonomy node file: /Users/paulli/anaconda3/envs/dash/lib/python3.9/site-packages/detaxa/taxonomy_db/nodes.dmp
2023-03-13 09:12 [INFO] taxonomy: Done parsing taxonomy node file.
2023-03-13 09:12 [INFO] taxonomy: Open merged taxonomy node file: /Users/paulli/anaconda3/envs/dash/lib/python3.9/site-packages/detaxa/taxonomy_db/merged.dmp
2023-03-13 09:12 [INFO] taxonomy: Done parsing merged taxonomy file.

In [2]:
import pandas as pd

df = pd.read_csv('data/bacterial_fungal_interactions.taxid.csv')
df

,Bacterial_associate_taxa,Found_in_16S-CC,Found_in_BSS,Found_in_previous_work,Fungal_host_taxa,Link,Source,Bacterial_associate_taxa_taxid,Fungal_host_taxa_taxid
0,Achromobacter,Yes,No,Yes,Trichoderma,https://doi.org/10.1111/1574-6968.12287,Isolation of oxalotrophic bacteria able to dis...,222,5543
1,Acinetobacter,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",469,5506
2,Agrococcus,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",46352,5506
3,Azospirillum,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",191,5506
4,Bacillus,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",1386,5506
...,...,...,...,...,...,...,...,...,...
5895,Trueperella,No,Yes,No,Ascoidea,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,1069494,27308
5896,Tsukamurella,No,Yes,No,Tritirachium,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,2060,1001993
5897,Variovorax,No,Yes,No,Cladophialophora,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,34072,82105
5898,Variovorax,No,Yes,No,Fonsecaea,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,34072,40354
5899,Yoonia,No,Yes,No,Fomitopsis,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,2211641,34474

In [3]:
df_temp = pd.read_csv('data/bacterial_taxonomy.csv')
df = df.merge(df_temp[['Bacterial_associate_taxa', 'Phylum']].drop_duplicates(), on='Bacterial_associate_taxa', how='left').rename(columns={'Phylum': 'Bacterial_phylum'})
df_temp = pd.read_csv('data/fungal_taxonomy.csv')
df = df.merge(df_temp[['Fungal_host_taxa', 'Phylum']].drop_duplicates(), on='Fungal_host_taxa', how='left').rename(columns={'Phylum': 'Fungal_phylum'})

df = df.fillna('na')

df

,Bacterial_associate_taxa,Found_in_16S-CC,Found_in_BSS,Found_in_previous_work,Fungal_host_taxa,Link,Source,Bacterial_associate_taxa_taxid,Fungal_host_taxa_taxid,Bacterial_phylum,Fungal_phylum
0,Achromobacter,Yes,No,Yes,Trichoderma,https://doi.org/10.1111/1574-6968.12287,Isolation of oxalotrophic bacteria able to dis...,222,5543,Proteobacteria,Ascomycota
1,Acinetobacter,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",469,5506,Proteobacteria,Ascomycota
2,Agrococcus,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",46352,5506,Actinobacteria,Ascomycota
3,Azospirillum,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",191,5506,Proteobacteria,Ascomycota
4,Bacillus,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",1386,5506,Firmicutes,Ascomycota
...,...,...,...,...,...,...,...,...,...,...,...
5895,Trueperella,No,Yes,No,Ascoidea,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,1069494,27308,Actinobacteria,Ascomycota
5896,Tsukamurella,No,Yes,No,Tritirachium,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,2060,1001993,Actinobacteria,Basidiomycota
5897,Variovorax,No,Yes,No,Cladophialophora,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,34072,82105,Proteobacteria,Ascomycota
5898,Variovorax,No,Yes,No,Fonsecaea,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,34072,40354,Proteobacteria,Ascomycota
5899,Yoonia,No,Yes,No,Fomitopsis,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,2211641,34474,Proteobacteria,Basidiomycota

In [3]:
def name2taxid(name, expand=False, fuzzy=False, reset=False, sk=None):
    x = t.name2taxid(name, expand=expand, max_matches=3, fuzzy=fuzzy, reset=reset, superkingdom=sk)
    if len(x):
        return x[0]
    else:
        return np.nan

In [4]:
df['Bacterial_associate_taxa_taxid'] = df.Bacterial_associate_taxa.apply(name2taxid)
df['Fungal_host_taxa_taxid'] = df.Fungal_host_taxa.apply(name2taxid)

NameError: name 't' is not defined

In [11]:
idx = df.Bacterial_associate_taxa_taxid.isna()
df.loc[idx, 'Bacterial_associate_taxa_taxid'] = df.loc[idx, 'Bacterial_associate_taxa'].apply(lambda x: name2taxid(x, expand=True, fuzzy=True, reset=True))

idx = df.Fungal_host_taxa_taxid.isna()
df.loc[idx, 'Fungal_host_taxa_taxid'] = df.loc[idx, 'Fungal_host_taxa'].apply(lambda x: name2taxid(x, expand=True, fuzzy=True, reset=True, sk='Eukaryota'))

In [4]:
df_taxa_idx = pd.DataFrame(df.Bacterial_associate_taxa.unique().tolist() + 
                           df.Fungal_host_taxa.unique().tolist() +
                           df.Bacterial_phylum.unique().tolist() +
                           df.Fungal_phylum.unique().tolist()
                          ).drop_duplicates().reset_index().rename(columns={0: 'name', 'index': 'id'})
df_taxa_idx = df_taxa_idx.fillna('na')
df_taxa_idx

        id                name
0        0       Achromobacter
1        1       Acinetobacter
2        2          Agrococcus
3        3        Azospirillum
4        4            Bacillus
...    ...                 ...
1049  1052       Basidiomycota
1050  1053       Zoopagomycota
1051  1054     Chytridiomycota
1052  1055            Porifera
1053  1056  Blastocladiomycota

[1054 rows x 2 columns]

In [5]:
df = df.merge(df_taxa_idx, how='left', left_on='Bacterial_associate_taxa', right_on='name').rename(columns={'id': 'bact_id'}).drop(columns=['name'])
df = df.merge(df_taxa_idx, how='left', left_on='Fungal_host_taxa', right_on='name').rename(columns={'id': 'fung_id'}).drop(columns=['name'])
df = df.merge(df_taxa_idx, how='left', left_on='Bacterial_phylum', right_on='name').rename(columns={'id': 'bact_phylum_id'}).drop(columns=['name'])
df = df.merge(df_taxa_idx, how='left', left_on='Fungal_phylum', right_on='name').rename(columns={'id': 'fung_phylum_id'}).drop(columns=['name'])
df

,Bacterial_associate_taxa,Found_in_16S-CC,Found_in_BSS,Found_in_previous_work,Fungal_host_taxa,Link,Source,Bacterial_associate_taxa_taxid,Fungal_host_taxa_taxid,Bacterial_phylum,Fungal_phylum,bact_id,fung_id,bact_phylum_id,fung_phylum_id
0,Achromobacter,Yes,No,Yes,Trichoderma,https://doi.org/10.1111/1574-6968.12287,Isolation of oxalotrophic bacteria able to dis...,222,5543,Proteobacteria,Ascomycota,0,678,1025,1050
1,Acinetobacter,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",469,5506,Proteobacteria,Ascomycota,1,679,1025,1050
2,Agrococcus,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",46352,5506,Actinobacteria,Ascomycota,2,679,109,1050
3,Azospirillum,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",191,5506,Proteobacteria,Ascomycota,3,679,1025,1050
4,Bacillus,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",1386,5506,Firmicutes,Ascomycota,4,679,119,1050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5895,Trueperella,No,Yes,No,Ascoidea,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,1069494,27308,Actinobacteria,Ascomycota,571,870,109,1050
5896,Tsukamurella,No,Yes,No,Tritirachium,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,2060,1001993,Actinobacteria,Basidiomycota,676,988,109,1052
5897,Variovorax,No,Yes,No,Cladophialophora,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,34072,82105,Proteobacteria,Ascomycota,35,868,1025,1050
5898,Variovorax,No,Yes,No,Fonsecaea,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,34072,40354,Proteobacteria,Ascomycota,35,886,1025,1050
5899,Yoonia,No,Yes,No,Fomitopsis,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,2211641,34474,Proteobacteria,Basidiomycota,677,910,1025,1052

In [6]:
df.to_csv('data/bacterial_fungal_interactions.taxid.csv', index=False)

In [8]:
# Vega nodes

df_nodes = pd.DataFrame()

df_temp = df[['Bacterial_associate_taxa', 'bact_phylum_id', 'bact_id']].rename(columns={'Bacterial_associate_taxa': 'name', 'bact_phylum_id': 'group', 'bact_id': 'index'})
df_nodes = pd.concat([df_nodes, df_temp])

df_temp = df[['Fungal_host_taxa', 'fung_phylum_id', 'fung_id']].rename(columns={'Fungal_host_taxa': 'name', 'fung_phylum_id': 'group', 'fung_id': 'index'})
df_nodes = pd.concat([df_nodes, df_temp])

# df_temp = df[['Bacterial_phylum', 'bact_phylum_id']].rename(columns={'Bacterial_phylum': 'name', 'bact_phylum_id': 'index'})
# df_temp['group'] = 99990
# df_nodes = pd.concat([df_nodes, df_temp])

# df_temp = df[['Fungal_phylum', 'fung_phylum_id']].rename(columns={'Fungal_phylum': 'name', 'fung_phylum_id': 'index'})
# df_temp['group'] = 99991
# df_nodes = pd.concat([df_nodes, df_temp])

df_nodes = df_nodes.drop_duplicates()
df_nodes

KeyError: "['bact_phylum_id', 'bact_id'] not in index"

In [9]:
# Vega links
# "links": [
#     {
#         "source": 1,
#         "target": 0,
#         "value": 1
#     },
df_links = df[['bact_id', 'fung_id', 'Found_in_previous_work']].drop_duplicates().rename(columns={'bact_id': 'source', 'fung_id': 'target', 'Found_in_previous_work': 'value'})
df_links

KeyError: "['bact_id', 'fung_id'] not in index"

In [54]:
data = {}
data['nodes'] = df_nodes.to_dict(orient='records')
data['links'] = df_links.to_dict(orient='records')

In [56]:
import json
# the json file where the output must be stored
out_file = open("data/bacterial_fungal_interactions.vega.orig.json", "w")
   
json.dump(data, out_file)

out_file.close()

### group

In [7]:
df_nodes = df.groupby('Bacterial_associate_taxa').count()['Fungal_host_taxa'].reset_index().rename(columns={'Bacterial_associate_taxa': 'name', 'Fungal_host_taxa': 'count'})
df_nodes['group'] = 'Bacteria'

df_temp = df.groupby('Fungal_host_taxa').count()['Bacterial_associate_taxa'].reset_index().rename(columns={'Fungal_host_taxa': 'name', 'Bacterial_associate_taxa': 'count'})
df_temp['group'] = 'Fungi'

df_nodes = pd.concat([df_nodes, df_temp])

df_nodes['index'] = df_nodes['name']

df_nodes = df_nodes.drop_duplicates()

df_nodes

               name  count     group           index
0       Abiotrophia      4  Bacteria     Abiotrophia
1    Acetitomaculum      1  Bacteria  Acetitomaculum
2    Acetobacterium      1  Bacteria  Acetobacterium
3    Acetomicrobium      1  Bacteria  Acetomicrobium
4     Achromobacter     18  Bacteria   Achromobacter
..              ...    ...       ...             ...
342          Xylona      3     Fungi          Xylona
343        Yarrowia      2     Fungi        Yarrowia
344       Zasmidium      2     Fungi       Zasmidium
345      Zoophthora      2     Fungi      Zoophthora
346          Zopfia      6     Fungi          Zopfia

[1025 rows x 4 columns]

In [8]:
df_links = df[['Bacterial_associate_taxa', 'Fungal_host_taxa', 'Found_in_previous_work']].drop_duplicates().rename(columns={'Bacterial_associate_taxa': 'source', 'Fungal_host_taxa': 'target', 'Found_in_previous_work': 'value'})
df_links

             source            target value
0     Achromobacter       Trichoderma   Yes
1     Acinetobacter          Fusarium   Yes
2        Agrococcus          Fusarium   Yes
3      Azospirillum          Fusarium   Yes
4          Bacillus          Fusarium   Yes
...             ...               ...   ...
5895    Trueperella          Ascoidea    No
5896   Tsukamurella      Tritirachium    No
5897     Variovorax  Cladophialophora    No
5898     Variovorax         Fonsecaea    No
5899         Yoonia        Fomitopsis    No

[5884 rows x 3 columns]

In [91]:
data = {}
data['nodes'] = df_nodes.to_dict(orient='records')
data['links'] = df_links.to_dict(orient='records')

In [92]:
import json
# the json file where the output must be stored
out_file = open("data/bacterial_fungal_interactions.vega.json", "w")
   
json.dump(data, out_file)

out_file.close()

### New

In [9]:
df

,Bacterial_associate_taxa,Found_in_16S-CC,Found_in_BSS,Found_in_previous_work,Fungal_host_taxa,Link,Source,Bacterial_associate_taxa_taxid,Fungal_host_taxa_taxid,Bacterial_phylum,Fungal_phylum,bact_id,fung_id,bact_phylum_id,fung_phylum_id
0,Achromobacter,Yes,No,Yes,Trichoderma,https://doi.org/10.1111/1574-6968.12287,Isolation of oxalotrophic bacteria able to dis...,222,5543,Proteobacteria,Ascomycota,0,678,1025,1050
1,Acinetobacter,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",469,5506,Proteobacteria,Ascomycota,1,679,1025,1050
2,Agrococcus,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",46352,5506,Actinobacteria,Ascomycota,2,679,109,1050
3,Azospirillum,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",191,5506,Proteobacteria,Ascomycota,3,679,1025,1050
4,Bacillus,Yes,No,Yes,Fusarium,https://doi.org/10.3389/fevo.2016.00116,"Diversity, Specificity, and Phylogenetic Relat...",1386,5506,Firmicutes,Ascomycota,4,679,119,1050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5895,Trueperella,No,Yes,No,Ascoidea,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,1069494,27308,Actinobacteria,Ascomycota,571,870,109,1050
5896,Tsukamurella,No,Yes,No,Tritirachium,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,2060,1001993,Actinobacteria,Basidiomycota,676,988,109,1052
5897,Variovorax,No,Yes,No,Cladophialophora,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,34072,82105,Proteobacteria,Ascomycota,35,868,1025,1050
5898,Variovorax,No,Yes,No,Fonsecaea,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,34072,40354,Proteobacteria,Ascomycota,35,886,1025,1050
5899,Yoonia,No,Yes,No,Fomitopsis,https://doi.org/10.1038/s42003-021-02693-y,Widespread bacterial diversity within the bact...,2211641,34474,Proteobacteria,Basidiomycota,677,910,1025,1052

In [20]:
df_nodes = df.groupby('Bacterial_associate_taxa').agg({
                        'Fungal_host_taxa_taxid': 'count', 
                        'bact_id':'first', 
                        'Bacterial_phylum': 'first',
                    }).reset_index().rename(columns={
                        'Bacterial_associate_taxa': 'name',
                        'Fungal_host_taxa_taxid': 'count', 
                        'bact_id': 'index', 
                        'Bacterial_phylum': 'phylum'
                    })

df_nodes['group'] = 'Bacteria'


df_temp = df.groupby('Fungal_host_taxa').agg({
                        'Bacterial_associate_taxa': 'count', 
                        'fung_id':'first', 
                        'Fungal_phylum': 'first'
                    }).reset_index().rename(columns={
                        'Fungal_host_taxa': 'name',
                        'Bacterial_associate_taxa': 'count', 
                        'fung_id': 'index', 
                        'Fungal_phylum': 'phylum'
                    })

df_temp['group'] = 'Fungi'

df_nodes = pd.concat([df_nodes, df_temp])

df_nodes = df_nodes.drop_duplicates()

df_nodes['index'] = df_nodes['index'].astype(int)

df_nodes

               name  count  index          phylum     group
0       Abiotrophia      4    123      Firmicutes  Bacteria
1    Acetitomaculum      1    124      Firmicutes  Bacteria
2    Acetobacterium      1    125      Firmicutes  Bacteria
3    Acetomicrobium      1    593   Synergistetes  Bacteria
4     Achromobacter     18      0  Proteobacteria  Bacteria
..              ...    ...    ...             ...       ...
342          Xylona      3    989      Ascomycota     Fungi
343        Yarrowia      2    976      Ascomycota     Fungi
344       Zasmidium      2    824      Ascomycota     Fungi
345      Zoophthora      2    971   Zoopagomycota     Fungi
346          Zopfia      6    972      Ascomycota     Fungi

[1025 rows x 5 columns]

In [21]:
df_links = df[['bact_id', 'fung_id', 'Found_in_16S-CC', 'Found_in_previous_work']].drop_duplicates().rename(columns={
            'bact_id': 'source', 
            'fung_id': 'target', 
            'Found_in_16S-CC': 'found_in_16s',
            'Found_in_previous_work': 'found_in_prev'
            })
df_links['source'] = df_links['source'].astype(int)
df_links['target'] = df_links['target'].astype(int)

df_links

      source  target found_in_16s found_in_prev
0          0     678          Yes           Yes
1          1     679          Yes           Yes
2          2     679          Yes           Yes
3          3     679          Yes           Yes
4          4     679          Yes           Yes
...      ...     ...          ...           ...
5895     571     870           No            No
5896     676     988           No            No
5897      35     868           No            No
5898      35     886           No            No
5899     677     910           No            No

[5884 rows x 4 columns]

In [22]:
df_links = df_links.merge(df_nodes[['index','name']], left_on='source', right_on='index', how='left').rename(columns={'name': 'source_name'}).drop(columns=['index'])
df_links = df_links.merge(df_nodes[['index','name']], left_on='target', right_on='index', how='left').rename(columns={'name': 'target_name'}).drop(columns=['index'])
df_links

,source,target,found_in_16s,found_in_prev,source_name,target_name
0,0,678,Yes,Yes,Achromobacter,Trichoderma
1,1,679,Yes,Yes,Acinetobacter,Fusarium
2,2,679,Yes,Yes,Agrococcus,Fusarium
3,3,679,Yes,Yes,Azospirillum,Fusarium
4,4,679,Yes,Yes,Bacillus,Fusarium
...,...,...,...,...,...,...
5879,571,870,No,No,Trueperella,Ascoidea
5880,676,988,No,No,Tsukamurella,Tritirachium
5881,35,868,No,No,Variovorax,Cladophialophora
5882,35,886,No,No,Variovorax,Fonsecaea
5883,677,910,No,No,Yoonia,Fomitopsis

In [23]:
data = {}

data['nodes'] = df_nodes.sort_values('index').to_dict(orient='records')
data['links'] = df_links.to_dict(orient='records')

import json
# the json file where the output must be stored
out_file = open("data/bacterial_fungal_interactions.vega.json", "w")
   
json.dump(data, out_file)

out_file.close()